# Generated by Django 4.2 on 2023-04-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testovoeapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='testovoeapi.category'),
        ),
    ]
