# Generated by Django 4.2 on 2023-04-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testovoeapi', '0009_alter_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=7, max_length=15),
        ),
    ]
